### ISSUE TITLE
You can only read by ID 

### ISSUE THREAD

**Issue by moparlakci** [lykmapipo/mongoose-gridfs#1]
At the moment you can only read by ID, even if you use the read function, it grabs the _id  from the object you pass to it and uses the readById method. Is it possible to read by metadata also or do you plan it in the future?

```
 var bucketfile = new Bucketfile({
    _id: fileid,
    metadata: { 
        bucket: bucketid
    }
 });

 var stream = bucketfile.read();
 stream.on('data', fn) ....`
```

**Comment by lykmapipo** [comment]
Hello,

Let me review it to see if we can add metadata for find.

I will appreciate pull request.

**Comment by lykmapipo** [comment]
@moparlakci So...since you get a valid [mongooose model](http://mongoosejs.com/docs/api.html#query-js) then all query operations are applicable to [GridFS](https://docs.mongodb.com/manual/core/gridfs/#the-files-collection) properties.

A special case come when you want to read actual file content. Please I advice to use stream. And yes use current provided methods unless [gridfs-stream](https://github.com/aheckmann/gridfs-stream) add some additional helpers.
